version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./data:/var/www
      - ./configs/xdebug/xdebug.ini:/var/conf.d/xdebug.ini
      - ./tests:/var/www/html/tests
    ports:
      - "9000:9000"
    environment:
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d:/var/conf.d/

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./data:/var/www
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/sites-available/default:/etc/nginx/sites-available/default
    ports:
      - "80:80"


